# Permalinks
permalink:            pretty

# reveal options
reveal:
  slide_separator:    "<hr />"
  vertical_separator: "<p>~~</p>"
  notes_separator:    "<p>Notes:</p>"
  title_slide:        true

# Setup
title:                Studio Methods — Slides
tagline:              "Markdown slides in Jekyll using reveal.js"
description:          "Slides for Louis Goldford's Studio Methods Seminar"
url:                  http://admhlt.github.io/jekyll-and-slide
baseurl:              /studio-methods-slides
markdown:             kramdown
kramdown:
  input:              GFM

collections:
  slides:
    output:           true
    permalink:        /:collection/:title/

# About/contact
author:
  name:               Louis Goldford  
  url:                https://www.louisgoldford.com  
  email:              Louis.Goldford@mh-luebeck.de  

# YAML defaults
defaults:
  - scope:
      path: ""
      type: slides
    values:
      layout: slides
